name: Trigger Coolify Deploy

on:
  push:
    branches:
      - main

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify deployment
        run: |
          curl -X GET \
           '${{ secrets.COOLIFY_DEPLOY_WEBHOOK_URL }}' \
           -H "Content-Type: application/json" \
           -H "authorization: ${{ secrets.COOLIFY_AUTH_KEY }}"
